### ISSUE TITLE
better error messages

### ISSUE THREAD

**Issue by tillmo** [ramyadirsumilli/rest_owl_api#23]
The API should produce better error messages, instead of "cannot GET" or cryptic java stacktraces.
For example: "method not recognized", "URL not found", etc.

**Comment by ramyadirsumilli** [comment]
I don't find any relevant work. 
Should all the get/post methods be added to a new function to send an error response ?

**Comment by tillmo** [comment]
see e.g. https://www.safaribooksonline.com/blog/2014/03/12/error-handling-express-js-applications/ , https://www.npmjs.com/package/express-error-handler
and  https://www.joyent.com/developers/node/design/errors

**Comment by tillmo** [comment]
another point is that you should catch Java excpections and return a more structured JSON object (containing the error) instead of just a Java stacktrace.

**Comment by ramyadirsumilli** [comment]
Done. 
Could you check the error messages.

**Comment by tillmo** [comment]
OK, but I always get `** Incorrect Arguments Passed**`, even if the method name is incorrect. In this case, I would expect "undefined method: xxx".

**Comment by ramyadirsumilli** [comment]
Could you please reverify ?

**Comment by tillmo** [comment]
I still get `** Incorrect Arguments Passed**`. Do you have an example where I do not get that?

**Comment by ramyadirsumilli** [comment]
Can you try with only incorrect method name but minimum 2 arguments passed ?
Example: `http://localhost:3000/e/http%3A%2F%2Fontohub.org%2Ftones%2Fwww.co-ode.org%2Fpizza.owl`

**Comment by tillmo** [comment]
yes, that works! However, it would also be good to have a specific error message if the wrong HTTP verb (GET / POST) is used.

**Comment by ramyadirsumilli** [comment]
I have already implemented that. 
If you try to call `logicalConsequences` using get then it returns `** Please use POST **`

**Comment by tillmo** [comment]
yes, I see. Now it would be good to return an error `** Incorrect number of arguments passed**` if the number of arguments is wrong, and `** Incorrect Arguments Passed**` if the number is correct but the argument themselves are wrong.

**Comment by ramyadirsumilli** [comment]
Error if the arguments passed is presently not possible, as the .js files only deal with the arguments as variables.
In order to do it, I will have to add a return variable to all the java methods.
I will try to do the changes after my submission ?
Would it be okay?

**Comment by tillmo** [comment]
yes, sure
